### ISSUE TITLE
deprecate legacy facts

### ISSUE THREAD

**Issue by vchepkov** [redhataccess/puppet-access_insights_client#12]
With puppet 8 released, legacy facts have been deprecated by default, `$::operatingsystemrelease` should be replaced with `$facts['os']['release']['full']`. I can submit an MR, but I am not sure how to properly modify spec tests
```
    let :facts do
      {:operatingsystemrelease => '6.10'}
    end
```

**Comment by ekohl** [comment]
I think you should use:
```ruby
let :facts do
  {
    operatingsystemrelease: '6.10',
    os: {
      release: {
        full: '6.10',
        major: '6',
      }
    }
  }
end
```

I know that rspec-puppet-facts does weird things with symbols and strings, but I think you don't have to and can just use symbols everywhere. I'd keep the legacy facts in because I'm not sure if old Puppet versions can run properly without legacy facts.

**Comment by vchepkov** [comment]
Thank you, @ekohl metadata requires puppet 6, and new facts were added already
I submitted https://github.com/redhataccess/puppet-access_insights_client/pull/13 for your consideration
