### ISSUE TITLE
Generate a tag

### ISSUE THREAD

**Issue by leonardoreboucas** [redhataccess/puppet-access_insights_client#4]
Please, generate a Tag I can use inside my work infra. 
Thanks.

**Comment by lphiri** [comment]
@leonardoreboucas  - are you interested in new version of the code on master?

**Comment by leonardoreboucas** [comment]
Yes. Actually there's none tag generated on this project. We need at least one to be setted on our internal gitlab, since we keep it synced to this one.

**Comment by lphiri** [comment]
@leonardoreboucas I have added a tag to match the last officially released version on puppetforge https://forge.puppet.com/lphiri/access_insights_client (v0.0.9)
Will tag a new version once tested.
